[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"
watchPatterns = ["frontend/**"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1
