"""initial_schema

Revision ID: cd7e2ce820c4
Revises: 
Create Date: 2026-03-02 20:29:51.325939
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7e2ce820c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=10), nullable=False),
    sa.Column('abreviacao', sa.String(length=10), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('apelido', sa.String(length=100), nullable=True),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('escudo_60', sa.String(length=500), nullable=True),
    sa.Column('escudo_45', sa.String(length=500), nullable=True),
    sa.Column('escudo_30', sa.String(length=500), nullable=True),
    sa.Column('url_editoria', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercado_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rodada_atual', sa.Integer(), nullable=False),
    sa.Column('status_mercado', sa.Integer(), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('game_over', sa.Boolean(), nullable=False),
    sa.Column('times_escalados', sa.Integer(), nullable=False),
    sa.Column('fechamento_timestamp', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('abreviacao', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rodadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('apelido', sa.String(length=200), nullable=False),
    sa.Column('apelido_abreviado', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('clube_id', sa.Integer(), nullable=False),
    sa.Column('posicao_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('pontos_num', sa.Float(), nullable=False),
    sa.Column('media_num', sa.Float(), nullable=False),
    sa.Column('preco_num', sa.Float(), nullable=False),
    sa.Column('variacao_num', sa.Float(), nullable=False),
    sa.Column('jogos_num', sa.Integer(), nullable=False),
    sa.Column('entrou_em_campo', sa.Boolean(), nullable=False),
    sa.Column('rodada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['posicao_id'], ['posicoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_atletas_clube_id', 'atletas', ['clube_id'], unique=False)
    op.create_index('ix_atletas_posicao_id', 'atletas', ['posicao_id'], unique=False)
    op.create_index('ix_atletas_status_id', 'atletas', ['status_id'], unique=False)
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodada_id', sa.Integer(), nullable=False),
    sa.Column('clube_casa_id', sa.Integer(), nullable=False),
    sa.Column('clube_visitante_id', sa.Integer(), nullable=False),
    sa.Column('clube_casa_posicao', sa.Integer(), nullable=True),
    sa.Column('clube_visitante_posicao', sa.Integer(), nullable=True),
    sa.Column('placar_oficial_mandante', sa.Integer(), nullable=True),
    sa.Column('placar_oficial_visitante', sa.Integer(), nullable=True),
    sa.Column('local', sa.String(length=200), nullable=True),
    sa.Column('partida_data', sa.DateTime(), nullable=True),
    sa.Column('valida', sa.Boolean(), nullable=False),
    sa.Column('aproveitamento_mandante', sa.JSON(), nullable=True),
    sa.Column('aproveitamento_visitante', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clube_casa_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['clube_visitante_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partidas_clube_casa_id', 'partidas', ['clube_casa_id'], unique=False)
    op.create_index('ix_partidas_clube_visitante_id', 'partidas', ['clube_visitante_id'], unique=False)
    op.create_index('ix_partidas_rodada_id', 'partidas', ['rodada_id'], unique=False)
    op.create_table('scouts_rodada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('rodada_id', sa.Integer(), nullable=False),
    sa.Column('clube_id', sa.Integer(), nullable=False),
    sa.Column('posicao_id', sa.Integer(), nullable=False),
    sa.Column('pontos_num', sa.Float(), nullable=False),
    sa.Column('preco_num', sa.Float(), nullable=False),
    sa.Column('variacao_num', sa.Float(), nullable=False),
    sa.Column('media_num', sa.Float(), nullable=False),
    sa.Column('entrou_em_campo', sa.Boolean(), nullable=False),
    sa.Column('gols', sa.Integer(), nullable=False),
    sa.Column('assistencias', sa.Integer(), nullable=False),
    sa.Column('finalizacao_trave', sa.Integer(), nullable=False),
    sa.Column('finalizacao_defendida', sa.Integer(), nullable=False),
    sa.Column('finalizacao_fora', sa.Integer(), nullable=False),
    sa.Column('passes_errados', sa.Integer(), nullable=False),
    sa.Column('faltas_sofridas', sa.Integer(), nullable=False),
    sa.Column('faltas_cometidas', sa.Integer(), nullable=False),
    sa.Column('cartao_amarelo', sa.Integer(), nullable=False),
    sa.Column('cartao_vermelho', sa.Integer(), nullable=False),
    sa.Column('impedimentos', sa.Integer(), nullable=False),
    sa.Column('desarmes', sa.Integer(), nullable=False),
    sa.Column('defesas', sa.Integer(), nullable=False),
    sa.Column('gols_sofridos', sa.Integer(), nullable=False),
    sa.Column('saldo_gol', sa.Integer(), nullable=False),
    sa.Column('defesa_penalti', sa.Integer(), nullable=False),
    sa.Column('gol_contra', sa.Integer(), nullable=False),
    sa.Column('penalti_cometido', sa.Integer(), nullable=False),
    sa.Column('penalti_sofrido', sa.Integer(), nullable=False),
    sa.Column('vitoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['atletas.id'], ),
    sa.ForeignKeyConstraint(['clube_id'], ['clubes.id'], ),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id', 'rodada_id', name='uq_scout_atleta_rodada')
    )
    op.create_index('ix_scouts_rodada_atleta_id', 'scouts_rodada', ['atleta_id'], unique=False)
    op.create_index('ix_scouts_rodada_rodada_id', 'scouts_rodada', ['rodada_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scouts_rodada_rodada_id', table_name='scouts_rodada')
    op.drop_index('ix_scouts_rodada_atleta_id', table_name='scouts_rodada')
    op.drop_table('scouts_rodada')
    op.drop_index('ix_partidas_rodada_id', table_name='partidas')
    op.drop_index('ix_partidas_clube_visitante_id', table_name='partidas')
    op.drop_index('ix_partidas_clube_casa_id', table_name='partidas')
    op.drop_table('partidas')
    op.drop_index('ix_atletas_status_id', table_name='atletas')
    op.drop_index('ix_atletas_posicao_id', table_name='atletas')
    op.drop_index('ix_atletas_clube_id', table_name='atletas')
    op.drop_table('atletas')
    op.drop_table('rodadas')
    op.drop_table('posicoes')
    op.drop_table('mercado_status')
    op.drop_table('clubes')
    # ### end Alembic commands ###
